Move documentation to lsst-the-doc
lsst/qserv-operator pull request #12
Opened 2020-04-24 09:01 UTC by fjammes

Improve documentation architecture

2020-05-05 15:30 UTC, jonathansick requested changes
Most reStructuredText syntax and style issues to address. See our [RestructuredText Style Guide](https://developer.lsst.io/restructuredtext/style.html) for more information.

2020-05-05 15:30 UTC, jonathansick commented on README.md
> +Access to [Qserv-operator documentation](https://qserv-operator.lsst.io/)
This might read better?

Read the [Qserv-operator documentation at https://qser-operator.lsst.io](https://qserv-operator.lsst.io/).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +================================
The is a first-level heading, so it needs to use `#` underline and overlines following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +-------------
The is a second-level heading, so it needs to use `=` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +Check first the `official k8s cheat sheet`_ for examples of `kubectl` basic commands.
Literals need double backticks:

```rst
``kubectl``
```

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +--------------------------
The is a second-level heading, so it needs to use `=` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +-------------------
The is a second-level heading, so it needs to use `=` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +--------------------------
The is a second-level heading, so it needs to use `=` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +---------------------------------------
The is a second-level heading, so it needs to use `=` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/admin/cheatsheet.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The is a this-level heading, so it needs to use `-` following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +--------------------
This is a top-level heading, so it needs to use `#` under and overlines following our style guide.

For more information, see the [RestructuredText Style Guide on headings](https://developer.lsst.io/restructuredtext/style.html#sections).

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +::
This is probably introducing an extra colon into the rendered docs. Instead, you might as well declare the content type:

```rst
.. code-block:: yaml
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +Travis-CI <https://travis-ci.org/lsst/qserv/>`__
```suggestion
Travis CI <https://travis-ci.org/lsst/qserv/>`__
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +~~~~~~~~~~~~~
```suggestion
=============
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +-  Access to a Kubernetes v1.14.2+ cluster.
```suggestion
-  Kubernetes version 1.14.2+.
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +~~~~~
```suggestion
=====
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +`qserv-operator` is based on *operator-sdk v0.15.2*
```suggestion
``qserv-operator`` is based on *operator-sdk v0.15.2*.
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +~~~~~~~~~~~~~~~~~~~
```suggestion
===================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
=================================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/devel/build.rst
> +Documentation is automatically built and generated on each Travis-CI build. This can also be performed manually by launching script below:
```suggestion
Documentation is automatically built and generated on each Travis CI build. This can also be performed manually by launching the script below:
```

2020-05-05 15:30 UTC, jonathansick commented on doc/index.rst
> +======================================
```suggestion
######################################
Qserv-operator |release| documentation
######################################
```

2020-05-05 15:30 UTC, jonathansick commented on doc/index.rst
> +Contents:
Delete?

2020-05-05 15:30 UTC, jonathansick commented on doc/index.rst
> +Generated on the |today|
```suggestion
Generated on the |today|.
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +-----------------------
```suggestion
#######################
Manage Qserv deployment
#######################
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~
```suggestion
=============
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +^^^^^^^^^^^^^^
```suggestion
--------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +-  Access to a Kubernetes v1.14.2+ cluster via a valid ``KUBECONFIG`` file.
Consider making a reStructuredText substitution for the Kubernetes version requirement since this appears in one other place.

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +   GKE).
Move up to the previous line?

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +-  Dynamic volume provisionning need to be available on the Kubernetes cluster (for example `kind <https://kind.sigs.k8s.io/>`__ for or
```suggestion
-  Dynamic volume provisioning need to be available on the Kubernetes cluster (for example `kind <https://kind.sigs.k8s.io/>`__ or
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
-----------------------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~~~~~~~~~
```suggestion
=====================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
=======================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +^^^^^^^^^^^^^^^^^^^^^
```suggestion
---------------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +    # This overlay is used on Travis-CI, o, top of kind
"Travis CI"

Is "o" a typo?

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +^^^^^^^^^^^^^^^^^^^^
```suggestion
--------------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
=========================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +::
The `::` syntax is a short cut for adding a colon to the end of the previous paragraph and make the next paragraph a code block. Right now this is adding an extra colon. I'd delete this and put a double colon at the end of `like`, above.

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
============================================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/main.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
========================
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +-----------
```suggestion
###########
Quick start
###########
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +~~~~~~~~~~~~~
```suggestion
=============
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
Install dependencies and add user to ``docker`` group
-----------------------------------------------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +    Restart session in order to take in account add to `docker` group.
```suggestion
    Restart session in order to take in account add to ``docker`` group.
```

Typo? "take in account add to"

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
--------------------------------
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +###############
```suggestion
^^^^^^^^^^^^^^^
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +##############
```suggestion
^^^^^^^^^^^^^^
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2020-05-05 15:30 UTC, jonathansick commented on doc/install/quick-start.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2020-05-11 06:43 UTC, fjammes commented on README.md
> +Access to [Qserv-operator documentation](https://qserv-operator.lsst.io/)
:+1:

2020-05-11 06:45 UTC, fjammes commented on doc/admin/cheatsheet.rst
> +-------------
:+1:

2020-05-11 06:45 UTC, fjammes commented on doc/admin/cheatsheet.rst
> +================================
:+1:

2020-05-11 06:45 UTC, fjammes commented on doc/admin/cheatsheet.rst
> +Check first the `official k8s cheat sheet`_ for examples of `kubectl` basic commands.
:+1:

2020-05-11 06:45 UTC, fjammes commented on doc/admin/cheatsheet.rst
> +--------------------------
:+1:

2020-05-11 06:47 UTC, fjammes commented on doc/install/quick-start.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
:+1:

2020-05-11 12:50 UTC, merged